name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  vcbuild64:
    name: "Windows Release|x64"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release --target all
          cmake --build . --config Release --target ntest
          cmake --build . --config Release --target xtest
          cmake --build . --config Release --target npytest
          cmake --build . --config Release --target xpytest
          cmake --build . --config Release --target gpytest
        shell: cmd

  vcbuild32:
    name: "Windows Release|x86"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release --target all
          cmake --build . --config Release --target ntest
          cmake --build . --config Release --target xtest
          cmake --build . --config Release --target npytest
          cmake --build . --config Release --target xpytest
          cmake --build . --config Release --target gpytest
        shell: cmd

  osx_x64:
    name: 'OSX x64'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release --target all
          cmake --build . --config Release --target ntest
          cmake --build . --config Release --target xtest
          cmake --build . --config Release --target npytest
          cmake --build . --config Release --target xpytest
          cmake --build . --config Release --target gpytest

  ubuntu_x64:
    name: 'OSX x64'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release --target all
          cmake --build . --config Release --target ntest
          cmake --build . --config Release --target xtest
          cmake --build . --config Release --target npytest
          cmake --build . --config Release --target xpytest
          cmake --build . --config Release --target gpytest
